// import Navbar from "./components/navbar";
// import About from './about/page'
// import Skills from './skills/page'
// import Projects from './projects/page'
// import Contact from './contact/page'
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' >
      <body
      >
        // <Navbar />
        // {children}
        // <About />
        // <Skills />
        // <Projects />
        // <Contact />
      </body>
    </html >
  );
}
