import localFont from "next/font/local";
import Navbar from "./components/navbar";
import About from './about/page'
import Skills from './skills/page'
import Projects from './projects/page'
import Contact from './contact/page'
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <About />
        <Skills />
        <Projects />
        <Contact />
      </body>
    </html >
  );
}
